### ISSUE TITLE
dev installation fails

### ISSUE THREAD

**Issue by diplodata** [cloudyr/aws.alexa#7]
Hi there. Any suggestions?

```
> devtools::install_github("cloudyr/aws.alexa", build_vignettes = TRUE)
Downloading GitHub repo cloudyr/aws.alexa@master
from URL https://api.github.com/repos/cloudyr/aws.alexa/zipball/master
Installing aws.alexa
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD build  \
  '/private/var/folders/_3/b8whcf8d1bb8w_lr2rrscb5m0000gn/T/RtmptBU1yt/devtools1239c67cc2d9c/cloudyr-aws.alexa-68383aa'  \
  --no-resave-data --no-manual 

* checking for file ‘/private/var/folders/_3/b8whcf8d1bb8w_lr2rrscb5m0000gn/T/RtmptBU1yt/devtools1239c67cc2d9c/cloudyr-aws.alexa-68383aa/DESCRIPTION’ ... OK
* preparing ‘aws.alexa’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--smart/-S has been removed.  Use +smart or -smart extension instead.
For example: pandoc -f markdown+smart -t markdown-smart.
Try pandoc --help for more information.
Error: processing vignette 'overview.Rmd' failed with diagnostics:
pandoc document conversion failed with error 2
Execution halted
Installation failed: Command failed (1)
```

**Comment by soodoku** [comment]
dear @diplodata:

Based on the next issue, do I assume that this is fixed?

Plus try, as you will see in the readme:
```
ghit::install_github("cloudyr/aws.alexa")
```

**Comment by soodoku** [comment]
1. And if it is still an issue then: since I can't replicate the issue, you need to send more info. on what OS, R version, etc. 

2. Also since it seems some build_vignettes issue on your machine, you can try with:
```
devtools::install_github("cloudyr/aws.alexa", build_vignettes = FALSE)

``

**Comment by diplodata** [comment]
Ah well that fixed the dev install. Other issue still live however.
